from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


LAMH_SAFETY_CONFIG_MAGIC = 0x4C534346
LAMH_SAFETY_CONFIG_VERSION = 1
LAMH_FLIGHT_MAX_ANGLE_DEG = 90
LAMH_SAFE_ANGLE_MACROS = (
    "LAMH_SAFE_ANGLE_PWM1_DEG",
    "LAMH_SAFE_ANGLE_PWM2_DEG",
    "LAMH_SAFE_ANGLE_PWM3_DEG",
    "LAMH_SAFE_ANGLE_PWM4_DEG",
)


@dataclass(frozen=True)
class LamhSafetyConfig:
    angles_deg: tuple[int, int, int, int]

    @classmethod
    def from_values(cls, values: Iterable[int]) -> "LamhSafetyConfig":
        angles = tuple(int(value) for value in values)
        if len(angles) != 4:
            raise ValueError("Lámh requires exactly four safe angles")
        if any(angle < 0 or angle > 90 for angle in angles):
            raise ValueError("Lámh safe angles must be whole degrees from 0 to 90")
        return cls((angles[0], angles[1], angles[2], angles[3]))

    @classmethod
    def defaults(cls) -> "LamhSafetyConfig":
        return cls((90, 90, 90, 90))


def render_lamh_safety_header(config: LamhSafetyConfig) -> str:
    lines = [
        "#ifndef LAMH_SAFETY_CONFIG_H",
        "#define LAMH_SAFETY_CONFIG_H",
        "",
        "/* Generated by Ogma Console. Build-time only; do not change in flight. */",
        f"#define LAMH_SAFETY_CONFIG_MAGIC 0x{LAMH_SAFETY_CONFIG_MAGIC:08X}U",
        f"#define LAMH_SAFETY_CONFIG_VERSION {LAMH_SAFETY_CONFIG_VERSION}U",
        "",
    ]
    lines.extend(
        f"#define {macro} {angle}"
        for macro, angle in zip(LAMH_SAFE_ANGLE_MACROS, config.angles_deg)
    )
    lines.append(f"#define LAMH_FLIGHT_MAX_ANGLE_DEG {LAMH_FLIGHT_MAX_ANGLE_DEG}")
    lines.extend(("", "#endif", ""))
    return "\n".join(lines)


def load_lamh_safety_config(path: Path) -> LamhSafetyConfig:
    text = path.read_text(encoding="utf-8")
    values: list[int] = []
    for macro in LAMH_SAFE_ANGLE_MACROS:
        match = re.search(rf"^\s*#define\s+{macro}\s+(-?\d+)\s*$", text, re.MULTILINE)
        if match is None:
            raise ValueError(f"missing {macro} in {path}")
        values.append(int(match.group(1)))
    return LamhSafetyConfig.from_values(values)


def write_lamh_safety_header(path: Path, config: LamhSafetyConfig) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(render_lamh_safety_header(config), encoding="utf-8")
    temporary.replace(path)
    return path


def save_lamh_safety_record(
    directory: Path,
    config: LamhSafetyConfig,
    env: str,
    header_path: Path,
    status: dict[str, object],
) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc)
    header = header_path.read_bytes()
    record = {
        "flashed_at_utc": timestamp.isoformat(),
        "env": env,
        "angles_deg": list(config.angles_deg),
        "header": str(header_path),
        "header_sha256": hashlib.sha256(header).hexdigest(),
        "status": status,
    }
    path = directory / f"lamh_safety_{timestamp.strftime('%Y%m%dT%H%M%SZ')}.json"
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    temporary.replace(path)
    return path
