from __future__ import annotations

import json
import zlib
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .flight_manifest import RadioPolicy


TEACHTAIRE_RADIO_CONFIG_MAGIC = 0x54435243
TEACHTAIRE_RADIO_CONFIG_SCHEMA_VERSION = 1


def radio_config_crc32(config: RadioPolicy) -> int:
    config.validate()
    payload = json.dumps(
        asdict(config),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    ).encode("ascii")
    return zlib.crc32(payload) & 0xFFFFFFFF


def render_teachtaire_radio_header(config: RadioPolicy) -> str:
    config.validate()
    return "\n".join(
        (
            "#ifndef TEACHTAIRE_RADIO_CONFIG_H",
            "#define TEACHTAIRE_RADIO_CONFIG_H",
            "",
            "/* Generated by Ogma Console. Build-time radio policy. */",
            f"#define TEACHTAIRE_RADIO_CONFIG_MAGIC 0x{TEACHTAIRE_RADIO_CONFIG_MAGIC:08X}U",
            f"#define TEACHTAIRE_RADIO_CONFIG_SCHEMA_VERSION {TEACHTAIRE_RADIO_CONFIG_SCHEMA_VERSION}U",
            f"#define TEACHTAIRE_RADIO_CONFIG_CRC32 0x{radio_config_crc32(config):08X}U",
            f"#define TEACHTAIRE_RADIO_CORE_PERIOD_MS {config.core_period_ms}U",
            f"#define TEACHTAIRE_RADIO_GPS_PERIOD_MS {config.gps_period_ms}U",
            f"#define TEACHTAIRE_RADIO_SLOW_PERIOD_MS {config.slow_period_ms}U",
            f"#define TEACHTAIRE_RADIO_DEEP_PERIOD_MS {config.health_period_ms}U",
            "",
            "#if TEACHTAIRE_RADIO_CORE_PERIOD_MS < 100U || TEACHTAIRE_RADIO_CORE_PERIOD_MS > 5000U",
            "#error \"invalid core radio period\"",
            "#endif",
            "#if TEACHTAIRE_RADIO_GPS_PERIOD_MS < 200U || TEACHTAIRE_RADIO_GPS_PERIOD_MS > 10000U",
            "#error \"invalid GPS radio period\"",
            "#endif",
            "#if TEACHTAIRE_RADIO_SLOW_PERIOD_MS < 200U || TEACHTAIRE_RADIO_SLOW_PERIOD_MS > 10000U",
            "#error \"invalid slow radio period\"",
            "#endif",
            "#if TEACHTAIRE_RADIO_DEEP_PERIOD_MS < 500U || TEACHTAIRE_RADIO_DEEP_PERIOD_MS > 30000U",
            "#error \"invalid deep radio period\"",
            "#endif",
            "",
            "#endif",
            "",
        )
    )


def write_teachtaire_radio_header(path: Path, config: RadioPolicy) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(render_teachtaire_radio_header(config), encoding="utf-8")
    temporary.replace(path)
    return path


def save_teachtaire_radio_record(
    directory: Path,
    config: RadioPolicy,
    env: str,
    header_path: Path,
    status: dict[str, Any],
) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(timezone.utc)
    crc32 = radio_config_crc32(config)
    payload = {
        "flashed_at_utc": timestamp.isoformat(),
        "env": env,
        "radio_config_crc32": f"{crc32:08x}",
        "radio": asdict(config),
        "header": str(header_path),
        "status": status,
    }
    path = directory / f"teachtaire_radio_{timestamp.strftime('%Y%m%dT%H%M%SZ')}_{crc32:08x}.json"
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    temporary.replace(path)
    return path
